
const char indexHTML[] PROGMEM =
"<!DOCTYPE html>"
"<meta charset='UTF-8'>"
"<meta  name='viewport' content='width=device-width,initial-scale=1,user-scalable=yes'/>"
"<title>" ESP_OTA_TITLE "</title>"

"<body style='font-family: Verdana,sans-serif; font-size: 14px; background-color: #060606; color: #fff;'>"
  "<div style='width:400px;padding:20px;border-radius:10px;border:solid 2px #e0e0e0;margin:auto;margin-top:20px;'>"
    "<div style='width:100%;text-align:center;font-size:18px;font-weight:bold;margin-bottom:12px;'>ESP OTA</div>"
    "<form method='POST' action='#' enctype='multipart/form-data' id='upload-form' style='width:100%;margin-bottom:8px;'>"
      "<input type='file' name='update'>"
      "<input type='submit' value='Update' style='float:right;'>"
    "</form>"
    "<div style='width:100%;background-color:#0e0e0e;border-radius:8px;'>"
      "<div id='pct' style='width:0%;background-color:#2196F3;padding:2px;border-radius:8px;color:white;text-align:center;'>0%</div>"
    "</div>"
  "</div>"
"</body>"
"<script>"
  "var pct = document.getElementById('pct');"
  "var form = document.getElementById('upload-form');"
  "form.addEventListener('submit', e=>{"
     "e.preventDefault();"
     "var file=new FormData(form);"
     "var r =new XMLHttpRequest();"
     "r.open('POST', '" ESP_OTA_WEB_PATH "');"
     "r.upload.addEventListener('progress', p=>{"
        "let w=Math.round((p.loaded/p.total)*100) + '%';"
        "if(p.lengthComputable){"
          "pct.innerHTML = w;"
          "pct.style.width = w;"
        "}"
        "if(w=='100%') pct.style.backgroundColor = '#04AA6D';"
     "});"
     "r.send(file);"
   "});"
"</script>";
